chore(code-style): added usabilla specific idea code style template
usabilla/js-styleguide pull request #11
Opened 2017-01-19 13:10 UTC by spirosikmd

2017-01-19 13:31 UTC, beerecca commented on idea-code-style/usabilla-idea-code-style.xml
> +    <option name="USE_SEMICOLON_AFTER_STATEMENT" value="false" />
Hmm really? What's our team preference on semicolons? I thought we liked them... :)

2017-01-19 13:32 UTC, spirosikmd commented on idea-code-style/usabilla-idea-code-style.xml
> +    <option name="USE_SEMICOLON_AFTER_STATEMENT" value="false" />
Oh yes we do. Why is that there? And why my editor is not complaining?

2017-01-19 13:34 UTC, beerecca commented
This doesn't do the stuff you mentioned about language defaults, is that possible to add? Maybe possible to also adding wallaby with the right config?
```* language-frameworks -> javascript -> es6
* language-frameworks -> javascript -> libraries -> jasmine-Definitely-Typed
* language-frameworks -> javascript -> code quality tools -> eslint
* language-frameworks -> node and npm -> enable```

2017-01-25 08:16 UTC, pietvanzoen requested changes
I believe this is all covered in the [`.editorconfig`](https://github.com/usabilla/js-styleguide/blob/master/node-project-template/.editorconfig). Provided you have the editor config plugin installed these rules apply.

However, we don't have instructions for that. So we should. Probably in the `/node-project-template/README.md`?

2017-01-25 08:20 UTC, spirosikmd commented
We should commit these anyway in this project I think. If we want to share other idea project settings we should think of another way. Should we go on and close this PR?

2017-01-25 08:25 UTC, pietvanzoen commented
So far everything inside `idea-code-style/usabilla-idea-code-style.xml` is just a duplication of what is in `.editorconfig`. We should be using the `.editorconfig` plugin for all projects that have an `.editorconfig`. And since `.editorconfig` trumps (ugh) the internal editor configuration, setting them in this code style xml actually has no effect.

2017-01-25 08:26 UTC, pietvanzoen commented
Wait, are you agreeing? I'm confused. 😛  Yes close unless there's something we want to add/change that isn't in `.editorconfig`

2017-01-25 08:27 UTC, pietvanzoen commented
Oh.. maybe add the .editorconfig stuff to the `node-project-template` readme?

2017-01-25 08:28 UTC, spirosikmd commented
I do agree! By close I mean abandon this PR. We should add the `.editorconfig` in another PR.

2017-01-25 08:30 UTC, spirosikmd commented
I created #16 for the editor config stuff.

2017-01-25 08:49 UTC, closed without merging