Some improvements (imho) to node template
usabilla/js-styleguide pull request #26
Opened 2017-04-07 11:53 UTC by gwkunze

- Removed FEDS from PR template
- Added jamine elsint plugin (no more need for lint-tests.sh)
- Moved dependencies to devDependencies
- Removed lodash (wasn't used)

2017-04-07 11:54 UTC, gwkunze commented on node-project-template/.eslintrc.json
> -  //"extends": "./node_modules/@usabilla/js-styleguide/eslint-config-usabilla/index.js"
Removed this because it didn't seem necessary to keep it commented out. If there was some reason for it I'll put it back

2017-04-07 11:55 UTC, gwkunze commented on node-project-template/package.json
> +  }
AFAICT all these dependencies are devDependencies, so moved them there, lodash wasn't used and would be installed unnecessarily so I removed it.

2017-04-07 11:55 UTC, pietvanzoen commented on node-project-template/.eslintrc.json
> -  //"extends": "./node_modules/@usabilla/js-styleguide/eslint-config-usabilla/index.js"
the build will now fail. 😛

2017-04-07 11:55 UTC, gwkunze commented on node-project-template/test/.eslintrc.json
> +    "jasmine/no-global-setup": 0
`_helpers/matchers.js` has a "global" `beforeEach` which this lint rule would complain about.

2017-04-07 11:56 UTC, pietvanzoen requested changes

2017-04-07 11:56 UTC, pietvanzoen commented on node-project-template/lint-tests.sh
> -focused_tests="$(grep -r -n 'fdescribe(\|fit(' ./test)"
Why was this removed?

2017-04-07 11:57 UTC, gwkunze commented
Also a question, why the non-standard location for jasmine.conf?

2017-04-07 11:57 UTC, gwkunze commented on node-project-template/lint-tests.sh
> -focused_tests="$(grep -r -n 'fdescribe(\|fit(' ./test)"
because that was manually linting which the jasmine eslint plugin already does for you

2017-04-07 11:58 UTC, pietvanzoen commented on node-project-template/lint-tests.sh
> -focused_tests="$(grep -r -n 'fdescribe(\|fit(' ./test)"
Did you find a rule that lints for focused tests?

2017-04-07 11:59 UTC, gwkunze commented on node-project-template/.eslintrc.json
> -  //"extends": "./node_modules/@usabilla/js-styleguide/eslint-config-usabilla/index.js"
ahh, ok

2017-04-07 11:59 UTC, gwkunze commented on node-project-template/lint-tests.sh
> -focused_tests="$(grep -r -n 'fdescribe(\|fit(' ./test)"
yup: https://github.com/tlvince/eslint-plugin-jasmine/blob/master/docs/rules/no-focused-tests.md

2017-04-07 12:02 UTC, gwkunze commented on node-project-template/lint-tests.sh
> -focused_tests="$(grep -r -n 'fdescribe(\|fit(' ./test)"
it also lints other useful stuff (`it()` with no expects, disabled tests, common typos (forgetting parentheses after `expect(foo).toBeUndefined;`)

2017-04-07 12:21 UTC, pietvanzoen commented on .eslintignore
> +node-project-template/**
linebreak

2017-04-07 12:22 UTC, pietvanzoen commented
@gwkunze what is the standard location for jasmine.json?

2017-04-07 12:26 UTC, gwkunze commented
instead of `/tests/**` `/spec/**` and jasmine.json in `/spec/config/jasmine.json` then you can run jasmine without the JASMINE_CONFIG_PATH argument

2017-04-07 12:31 UTC, gwkunze commented on node-project-template/.eslintrc.json
> -  //"extends": "./node_modules/@usabilla/js-styleguide/eslint-config-usabilla/index.js"
Made build succeed without having to have this commented out. Woo! .eslintignore ftw

2017-04-08 09:16 UTC, spirosikmd approved these changes

2017-04-10 13:49 UTC, pietvanzoen approved these changes

2017-04-10 15:30 UTC, merged